# FILE: .azure/environment.yml
# This file defines the software environment for the deployment.

$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: churn-prod-env
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
conda_file:
  name: project_environment
  channels:
    - conda-forge
  dependencies:
    - python=3.9
    - pip
    - pip:
      - pandas
      - scikit-learn
      - xgboost
      - imbalanced-learn
      - joblib
      - azureml-defaults